version: "3.8"

services:
  # prestashop
  prestashop:
    build:
      context: ./prestashop
      dockerfile: Dockerfile
    container_name: prestashop
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: user
      DB_PASSWD: password
    volumes:
      - prestashop_data:/var/www/html
    networks:
      - prestashop_network

  # mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - prestashop_network

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 64M
    networks:
      - prestashop_network

  # reverse proxy nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - prestashop
      - phpmyadmin
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - prestashop_network

volumes:
  mysql_data:
  prestashop_data:

networks:
  prestashop_network:
    driver: bridge
