global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "votre-email@gmail.com"
  smtp_auth_username: "votre-email@gmail.com"
  smtp_auth_password: "votre-mot-de-passe-app"

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"
  routes:
    - match:
        severity: critical
      receiver: email-critical
    - match:
        severity: warning
      receiver: email-warning

receivers:
  - name: "web.hook"
    webhook_configs:
      - url: "http://127.0.0.1:5001/"

  # Alertes par email
  - name: "email-critical"
    email_configs:
      - to: "admin@example.com"
        subject: "🚨 Alerte Critique - PrestaShop"
        body: |
          Alerte critique détectée !

          Détails:
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
          - {{ .Annotations.description }}
          {{ end }}

  - name: "email-warning"
    email_configs:
      - to: "admin@example.com"
        subject: "⚠️ Alerte Warning - PrestaShop"
        body: |
          Alerte warning détectée.

          Détails:
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
          {{ end }}

  # Alertes Slack (optionnel)
  - name: "slack-notifications"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
        channel: "#alerts"
        title: "PrestaShop Alert"
        text: "{{ range .Alerts }}{{ .Annotations.description }}{{ end }}"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
