name: Build and Push to Docker Hub

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push PrestaShop image
        uses: docker/build-push-action@v5
        with:
          context: ./prestashop
          file: ./prestashop/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/prestashop-custom:latest

      - name: Build and push NGINX image
        uses: docker/build-push-action@v5
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-reverse-proxy:latest
